# syntax = docker/dockerfile:1.7

FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

# Install OS dependencies required by Prisma & OpenSSL
RUN apk add --no-cache openssl libc6-compat

COPY package.json pnpm-lock.yaml* ./
COPY prisma ./prisma
COPY prisma.config.ts ./prisma.config.ts

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm prisma generate

CMD ["pnpm", "worker"]
